apiVersion: v2
name: simple-unconference
description: Self-hostable unconference scheduling app (sqlite or postgres backend)
type: application
version: 0.1.0
appVersion: "0.2.1"
home: https://github.com/enyineer/simple-unconference
sources:
  - https://github.com/enyineer/simple-unconference
maintainers:
  - name: Nico Enking
    url: https://github.com/enyineer
kubeVersion: ">=1.23.0-0"
